name: Deploy Static Website

# The trigger event (runs the action when you push to GitHub)
on:
  push:
    branches:
      - main   # Runs when you push to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # This tells GitHub to use a computer running Linux

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Downloads your website code

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Install Terraform (to work with the cloud)
      
    - name: Run Terraform Commands
      run: |
        terraform init       # Prepares Terraform for use
        terraform apply -auto-approve  # Automatically creates your cloud resources and uploads the website

    - name: Upload to S3 Bucket (AWS)
      run: |
        aws s3 sync ./website/ s3://my-website-bucket --delete  # Uploads website files to AWS S3

